version: '3.6'
services:
  app:
    image: openjdk:17
    ports:
      - 8085:8080
    tty: true
    volumes:
      - ./todo:/srv:cached
    working_dir: /srv
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:8.0
    container_name: springboot-mysql
    volumes:
      - ./mysql/log/:/var/lib/mysql
      - ./mysql/sql_init/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/sql_init/init_data.sql:/docker-entrypoint-initdb.d/init_data.sql
    ports:
      - 3326:3306
    environment:
      MYSQL_DATABASE: "sample" # この場合sampleというデータベースが作成されます
      MYSQL_ROOT_USER: "root" # rootユーザーはパスワードを設定しないとエラーでます
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Asia/Tokyo"

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: vue-fornt
    ports:
      - 8089:8080
    volumes:
      - ./front:/front
    tty: true
    stdin_open: true

